### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by adriaanmyob** [splitio/.net-client#113]
Hi,

We are using this .NET SDK and we notice a lot of traffic and latency issues within our New Relic reports.

What optimizations do you recommend to improve performance with this SDK?

Thanks.

**Comment by NicoZelaya** [comment]
Hey Adrian!

Closing the issue as I understand it went through our Support platform. If this is not the case, feel free to reopen or contact support@split.io.

Thanks!
Nico.
