### ISSUE TITLE
Remove NLog dependency

### ISSUE THREAD

**Issue by shatl** [splitio/.net-client#78]
Please replace NLog dependency with Microsoft.Extensions.Logging or Common.Logging

**Comment by patricioe** [comment]
Hi,

Is using NLog not a good practice?

**Comment by shatl** [comment]
This is an extra dependency on particular logging framework.
Let's say we use log4net or Serilog in our project. Both of them (including NLog) have common.logging and microsoft.logging adapters.

**Comment by patricioe** [comment]
Thanks for the feedback. We'll work on it.

**Comment by SenhorCastor** [comment]
Sorry for the delay, this was fixed on 3.1.2. Closing this.

Thanks for the feedback!
