### ISSUE TITLE
Remove StackExhange.Redis dependency

### ISSUE THREAD

**Issue by shatl** [splitio/.net-client#80]
Please implement Redis caching as separate package

**Comment by patricioe** [comment]
@shatl is it conflicting with other packages in your project? or is this just a nice to have?

**Comment by shatl** [comment]
This is Dependency Inversion Principle violation.

I don't use Redis in my project, why should I have a dependency on it?

**Comment by SenhorCastor** [comment]
Sorry for the delay, this was fixed in version 3.3.0.

Closing. Thanks for the feedback!
